"""
Hermes Ops Kit — Environment Renderer

Reads provider secrets from Vaultwarden via the SecretBackend interface
and renders ~/.hermes/.env.generated.

Uses the mapping defined in config/env_projection.yaml (spec section 14).
Never logs raw rendered values.
"""

from __future__ import annotations

import os

from security.fingerprints import secret_fingerprint  # pyright: ignore[reportMissingImports]
from security.secret_backend import SecretBackend  # pyright: ignore[reportMissingImports]


# Default projection mapping (env var → internal secret ref).
# Override by loading config/env_projection.yaml at runtime.
DEFAULT_PROJECTION: dict[str, str] = {
    # OpenAI
    "OPENAI_API_KEY": "hermes/openai/api_key",
    "OPENAI_PROJECT_ID": "hermes/openai/project_id",
    # Anthropic
    "ANTHROPIC_API_KEY": "hermes/anthropic/api_key",
    # Google / Gemini
    "GEMINI_API_KEY": "hermes/google/gemini_api_key",
    "GOOGLE_API_KEY": "hermes/google/gemini_api_key",
    "GOOGLE_APPLICATION_CREDENTIALS_JSON": "hermes/google/application_credentials_json",
    # DeepSeek
    "DEEPSEEK_API_KEY": "hermes/deepseek/api_key",
    "DEEPSEEK_BASE_URL": "hermes/deepseek/base_url",
    "DEEPSEEK_ANTHROPIC_BASE_URL": "hermes/deepseek/anthropic_base_url",
    "DEEPSEEK_DEFAULT_MODEL": "hermes/deepseek/default_model",
    "DEEPSEEK_REASONING_MODEL": "hermes/deepseek/reasoning_model",
    # GitHub
    "GITHUB_APP_ID": "hermes/github/app_id",
    "GITHUB_INSTALLATION_ID": "hermes/github/installation_id",
    "GITHUB_TOKEN": "hermes/github/token",
    "GH_TOKEN": "hermes/github/token",
}


def render_env_content(
    backend: SecretBackend,
    projection: dict[str, str] | None = None,
) -> str:
    """Read all secrets from *backend* and render .env.generated content.

    Returns the rendered content as a string.  Never prints it.
    """
    mapping = projection or DEFAULT_PROJECTION

    lines: list[str] = [
        "# ~/.hermes/.env.generated",
        "# Generated by hermes-key-rotate.py",
        "# Do not edit manually.",
        "",
    ]

    seen_secrets: set[str] = set()
    for env_var, secret_ref in sorted(mapping.items()):
        secret = backend.get_secret(secret_ref)
        if secret and secret.value:
            value = secret.value
            fp, last4 = secret_fingerprint(value)
            lines.append(f"# fingerprint={fp} last4={last4}")
            lines.append(f'{env_var}="{value}"')
            seen_secrets.add(secret_ref)
        else:
            lines.append(f"# {env_var}=<NOT FOUND: {secret_ref}>")

    lines.append("")
    return "\n".join(lines)


def render_env(
    backend: SecretBackend,
    output_path: str | None = None,
    projection: dict[str, str] | None = None,
) -> str:
    """Render .env.generated and atomically write to *output_path*.

    Returns the path written.
    """
    from env.atomic_write import atomic_write  # pyright: ignore[reportMissingImports]

    content = render_env_content(backend, projection)
    target = output_path or os.path.expanduser("~/.hermes/.env.generated")
    atomic_write(target, content)
    return target
